In [ ]:
Basic Array Creation

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
arr

In [ ]:
a = [1,2,3,4]
a

In [ ]:
a = [1 , "Hello",3.5]
a

In [ ]:
arr = np.array([1,3.5,"hello"])
arr

In [ ]:
arr = np.array([1,3.5,4,6])
arr

In [4]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
Array Generation Function

In [6]:
arr = np.arange(0,11,3)
arr

array([0, 3, 6, 9])

In [7]:
arr = np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [8]:
arr = np.zeros((5,7))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
arr = np.ones(7)
arr

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr = np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
arr = np.linspace(1,11,2)
arr

array([ 1., 11.])

In [ ]:
Random Generation Function

In [5]:
arr = np.random.rand(3) 
arr

array([0.5640057, 0.4739134, 0.0733895])

In [8]:
arr = np.random.randn(4)
arr

array([-1.67634106, -0.77880602,  1.63907052, -1.20766012])

In [9]:
arr = np.random.randint(10,30,20)
arr

array([28, 16, 28, 14, 25, 12, 15, 23, 25, 18, 21, 24, 12, 18, 16, 13, 16,
       10, 11, 13], dtype=int32)

In [ ]:
Array Attributes

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.shape

(3, 3)

In [15]:
arr.size

9

In [18]:
arr.dtype

dtype('int64')

In [ ]:
Array Methods

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr.min()

np.int64(1)

In [14]:
arr.max()

np.int64(9)

In [15]:
arr.sum()

np.int64(45)

In [20]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [21]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [22]:
arr.mean()

np.float64(5.0)

In [23]:
arr.std()

np.float64(2.581988897471611)

In [25]:
arr.argmax()

np.int64(8)

In [27]:
arr.argmin()

np.int64(0)

In [ ]:
Reshaping and Resizing

In [3]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [13]:
a = np.reshape(arr,(6,5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [12]:
a = np.resize(arr,(5,2))
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
Array Indexing amd Slicing

In [27]:
import numpy as np

In [ ]:
Numpy Indexing and Slicing of Vector

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[7]

np.int64(18)

In [5]:
arr[1:6]

array([12, 13, 14, 15, 16])

In [6]:
arr[ :5]

array([11, 12, 13, 14, 15])

In [7]:
arr[ : ]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
Numpy Indexing and Slicing of Matrix

In [14]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [25]:
arr[0,1]

np.int64(2)

In [26]:
slice = arr[3:,3:,]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
Boolean Indexing

In [28]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index = arr %2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [30]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
Array Operaton

In [11]:
import numpy as np

In [ ]:
Arithmetic Operation

In [20]:
a1 = np.array([1,2,3,4,5])
a2 = np.array ([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [9]:
arr3 = a1 + a2
arr3

array([ 7,  9, 11, 13, 15])

In [15]:
arr = a1 - a2
arr

array([-5, -5, -5, -5, -5])

In [17]:
arr = a1 * a2
arr

array([ 6, 14, 24, 36, 50])

In [18]:
arr = a1 / a2
arr

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [19]:
arr = a1 // a2
arr

array([0, 0, 0, 0, 0])

In [21]:
arr = a1 ** a2
arr

array([      1,     128,    6561,  262144, 9765625])

In [24]:
arr2 = arr2 - 5
arr2

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
Broadcasting

In [18]:
l = [10,20,30,40]
arr = np.array(l)


In [19]:
arr + 10

array([20, 30, 40, 50])

In [20]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [21]:
arr2 * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [ ]:
Shallow copy

In [25]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [27]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [58]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
Deep copy

In [59]:
a
b = a
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
a


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
Matrix Operation

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [5]:
A

array([[1, 2],
       [3, 4]])

In [6]:
B

array([[5, 6],
       [7, 8]])

In [7]:
A @ B

array([[19, 22],
       [43, 50]])

In [8]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
Stacking Array

In [10]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [14]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
Spliting Array

In [20]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [23]:
np.vsplit(c,2)


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
Numpy Exercise

In [4]:
import numpy as np

In [ ]:
Valid Sudoku

In [12]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]   
])

In [17]:
b = np.sum(s,axis = 1)
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
        print("for rows it is valid")

for rows it is valid


In [21]:
c = np.sum(s,axis = 0)
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("for column it is valid")
    

for column it is valid


In [22]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [23]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [25]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])



[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [26]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
General Question

In [29]:
import numpy as np

# Column: [Age,Math Marks, Science Marks]
data = np.array([
     [18,85,78],   #Student 1
     [19,92,88],   #Student 2
     [17,76,95],   #Student 3
     [18,65,70],   #Student 4
     [20,95,85]    #Student 5 
])

In [29]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [34]:
#Find the average age of student.
np.mean(data[:,0])

np.float64(18.4)

In [35]:
#Extract Math marks of all student.
data[:,1]

array([85, 92, 76, 65, 95])

In [37]:
#Find the highest science marks.
np.max(data[:,2])

np.int64(95)

In [41]:
#Get details of the student who scored more than 90 in math.
data[data[:,1]>90]

array([[19, 92, 88],
       [20, 95, 85]])

In [13]:
#Increase Math marks of all student by 5.
data[0:1] += 5
data

array([[28, 95, 88],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 95, 85]])

In [14]:
data

array([[28, 95, 88],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 95, 85]])

In [16]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [18]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis = 0)

array([82.6, 83.2])

In [24]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >=80)]

array([[19, 92, 88],
       [20, 95, 85]])

In [30]:
#Replace of Science marks < 75 with 0 .
data[:,2][data[:,2]< 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 95, 85]])