Numpy Exercise

In [1]:
import numpy as np

Valid Sudoku

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]   
])

In [3]:
b = np.sum(s,axis = 1)
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
        print("for rows it is valid")

for rows it is valid


In [4]:
c = np.sum(s,axis = 0)
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("for column it is valid")
    

for column it is valid


In [5]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [6]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [7]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])


[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [10]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Question

In [11]:
import numpy as np

# Column: [Age,Math Marks, Science Marks]
data = np.array([
     [18,85,78],   #Student 1
     [19,92,88],   #Student 2
     [17,76,95],   #Student 3
     [18,65,70],   #Student 4
     [20,95,85]    #Student 5 
])

In [12]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [13]:
#Find the average age of student.
np.mean(data[:,0])

np.float64(18.4)

In [14]:
#Extract Math marks of all student.
data[:,1]

array([85, 92, 76, 65, 95])

In [15]:
#Find the highest science marks.
np.max(data[:,2])

np.int64(95)

In [16]:
#Get details of the student who scored more than 90 in math.
data[data[:,1]>90]

array([[19, 92, 88],
       [20, 95, 85]])

In [17]:
#Increase Math marks of all student by 5.
data[0:1] += 5
data

array([[23, 90, 83],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 95, 85]])

In [21]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

2

In [20]:
data

array([[23, 90, 83],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 95, 85]])

In [22]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis = 0)

array([83.6, 84.2])

In [23]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >=80)]

array([[23, 90, 83],
       [19, 92, 88],
       [20, 95, 85]])

In [24]:
#Replace of Science marks < 75 with 0 .
data[:,2][data[:,2]< 75] = 0
data

array([[23, 90, 83],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 95, 85]])